// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcC2_PepQtfdC2ISTXtapq2R4MVWgbl0A',
    appId: '1:563121899307:web:810a993c9ca5793265e76e',
    messagingSenderId: '563121899307',
    projectId: 'razakevent',
    authDomain: 'razakevent.firebaseapp.com',
    storageBucket: 'razakevent.firebasestorage.app',
    measurementId: 'G-S4ENR570NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgaIhSFXIOHOHokCNbpoJXnKKlQGPg1eQ',
    appId: '1:563121899307:android:db3653565b27a30f65e76e',
    messagingSenderId: '563121899307',
    projectId: 'razakevent',
    storageBucket: 'razakevent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXFB0ZdnBq794zOKi0oCczFDtX0RL3i2E',
    appId: '1:563121899307:ios:fe2a33cda79e259265e76e',
    messagingSenderId: '563121899307',
    projectId: 'razakevent',
    storageBucket: 'razakevent.firebasestorage.app',
    iosBundleId: 'my.utm.razakevent.razakEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXFB0ZdnBq794zOKi0oCczFDtX0RL3i2E',
    appId: '1:563121899307:ios:533d40b7e4a8575a65e76e',
    messagingSenderId: '563121899307',
    projectId: 'razakevent',
    storageBucket: 'razakevent.firebasestorage.app',
    iosBundleId: 'no',
  );
}
